type Mutation {
    createUser(dados: InputUsuario): Usuario
    updateUser(
        filtro: FiltroUsuario 
        dados: InputUsuario
    ):Usuario
    deleteUser(filtro: FiltroUsuario!): Usuario
}


# updateUser: Usuario
#     deleteUser: Usuario
#     createPerfil: Perfil
#     updatePerfil: Perfil
#     deletePerfil: Perfil